/*
 * Service Registry Fleet Manager
 *
 * Managed Service Registry cloud.redhat.com API Management API that lets you create new registry instances. Registry is a datastore for standard event schemas and API designs. Service Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Registry is an Managed version of upstream project called Apicurio Registry. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.
 *
 * API version: 0.0.5
 * Contact: rhosak-eval-support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package registrymgmtclient

import (
	"encoding/json"
)

// RegistryRest struct for RegistryRest
type RegistryRest struct {

	Id string `json:"id"`

	Kind *string `json:"kind,omitempty"`

	Href *string `json:"href,omitempty"`

	Status RegistryStatusValueRest `json:"status"`

	RegistryUrl string `json:"registryUrl"`

	// User-defined Registry name. Does not have to be unique.
	Name *string `json:"name,omitempty"`

	// Identifier of a multi-tenant deployment, where this Service Registry instance resides.
	RegistryDeploymentId *int32 `json:"registryDeploymentId,omitempty"`

	// Registry instance owner
	Owner *string `json:"owner,omitempty"`

}

// NewRegistryRest instantiates a new RegistryRest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryRest(id string, status RegistryStatusValueRest, registryUrl string) *RegistryRest {
	this := RegistryRest{}
	this.Id = id
	this.Status = status
	this.RegistryUrl = registryUrl
	return &this
}

// NewRegistryRestWithDefaults instantiates a new RegistryRest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryRestWithDefaults() *RegistryRest {
	this := RegistryRest{}









	return &this
}


// GetId returns the Id field value
func (o *RegistryRest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegistryRest) SetId(v string) {
	o.Id = v
}


// GetKind returns the Kind field value if set, zero value otherwise.
func (o *RegistryRest) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *RegistryRest) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *RegistryRest) SetKind(v string) {
	o.Kind = &v
}


// GetHref returns the Href field value if set, zero value otherwise.
func (o *RegistryRest) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *RegistryRest) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *RegistryRest) SetHref(v string) {
	o.Href = &v
}


// GetStatus returns the Status field value
func (o *RegistryRest) GetStatus() RegistryStatusValueRest {
	if o == nil {
		var ret RegistryStatusValueRest
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetStatusOk() (*RegistryStatusValueRest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RegistryRest) SetStatus(v RegistryStatusValueRest) {
	o.Status = v
}


// GetRegistryUrl returns the RegistryUrl field value
func (o *RegistryRest) GetRegistryUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryUrl
}

// GetRegistryUrlOk returns a tuple with the RegistryUrl field value
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetRegistryUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RegistryUrl, true
}

// SetRegistryUrl sets field value
func (o *RegistryRest) SetRegistryUrl(v string) {
	o.RegistryUrl = v
}


// GetName returns the Name field value if set, zero value otherwise.
func (o *RegistryRest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RegistryRest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RegistryRest) SetName(v string) {
	o.Name = &v
}


// GetRegistryDeploymentId returns the RegistryDeploymentId field value if set, zero value otherwise.
func (o *RegistryRest) GetRegistryDeploymentId() int32 {
	if o == nil || o.RegistryDeploymentId == nil {
		var ret int32
		return ret
	}
	return *o.RegistryDeploymentId
}

// GetRegistryDeploymentIdOk returns a tuple with the RegistryDeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetRegistryDeploymentIdOk() (*int32, bool) {
	if o == nil || o.RegistryDeploymentId == nil {
		return nil, false
	}
	return o.RegistryDeploymentId, true
}

// HasRegistryDeploymentId returns a boolean if a field has been set.
func (o *RegistryRest) HasRegistryDeploymentId() bool {
	if o != nil && o.RegistryDeploymentId != nil {
		return true
	}

	return false
}

// SetRegistryDeploymentId gets a reference to the given int32 and assigns it to the RegistryDeploymentId field.
func (o *RegistryRest) SetRegistryDeploymentId(v int32) {
	o.RegistryDeploymentId = &v
}


// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *RegistryRest) GetOwner() string {
	if o == nil || o.Owner == nil {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryRest) GetOwnerOk() (*string, bool) {
	if o == nil || o.Owner == nil {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *RegistryRest) HasOwner() bool {
	if o != nil && o.Owner != nil {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *RegistryRest) SetOwner(v string) {
	o.Owner = &v
}


func (o RegistryRest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	
	if true {
		toSerialize["id"] = o.Id
	}
    
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
    
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
    
	if true {
		toSerialize["status"] = o.Status
	}
    
	if true {
		toSerialize["registryUrl"] = o.RegistryUrl
	}
    
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
    
	if o.RegistryDeploymentId != nil {
		toSerialize["registryDeploymentId"] = o.RegistryDeploymentId
	}
    
	if o.Owner != nil {
		toSerialize["owner"] = o.Owner
	}
    
	return json.Marshal(toSerialize)
}

type NullableRegistryRest struct {
	value *RegistryRest
	isSet bool
}

func (v NullableRegistryRest) Get() *RegistryRest {
	return v.value
}

func (v *NullableRegistryRest) Set(val *RegistryRest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryRest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryRest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryRest(val *RegistryRest) *NullableRegistryRest {
	return &NullableRegistryRest{value: val, isSet: true}
}

func (v NullableRegistryRest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryRest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

