/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * API version: 1.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkamgmtclient

import (
	"encoding/json"
)

// SupportedKafkaInstanceTypesListAllOf struct for SupportedKafkaInstanceTypesListAllOf
type SupportedKafkaInstanceTypesListAllOf struct {

	Items *[]SupportedKafkaInstanceType `json:"items,omitempty"`

}

// NewSupportedKafkaInstanceTypesListAllOf instantiates a new SupportedKafkaInstanceTypesListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedKafkaInstanceTypesListAllOf() *SupportedKafkaInstanceTypesListAllOf {
	this := SupportedKafkaInstanceTypesListAllOf{}
	return &this
}

// NewSupportedKafkaInstanceTypesListAllOfWithDefaults instantiates a new SupportedKafkaInstanceTypesListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedKafkaInstanceTypesListAllOfWithDefaults() *SupportedKafkaInstanceTypesListAllOf {
	this := SupportedKafkaInstanceTypesListAllOf{}


	return &this
}


// GetItems returns the Items field value if set, zero value otherwise.
func (o *SupportedKafkaInstanceTypesListAllOf) GetItems() []SupportedKafkaInstanceType {
	if o == nil || o.Items == nil {
		var ret []SupportedKafkaInstanceType
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedKafkaInstanceTypesListAllOf) GetItemsOk() (*[]SupportedKafkaInstanceType, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SupportedKafkaInstanceTypesListAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []SupportedKafkaInstanceType and assigns it to the Items field.
func (o *SupportedKafkaInstanceTypesListAllOf) SetItems(v []SupportedKafkaInstanceType) {
	o.Items = &v
}


func (o SupportedKafkaInstanceTypesListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
    
	return json.Marshal(toSerialize)
}

type NullableSupportedKafkaInstanceTypesListAllOf struct {
	value *SupportedKafkaInstanceTypesListAllOf
	isSet bool
}

func (v NullableSupportedKafkaInstanceTypesListAllOf) Get() *SupportedKafkaInstanceTypesListAllOf {
	return v.value
}

func (v *NullableSupportedKafkaInstanceTypesListAllOf) Set(val *SupportedKafkaInstanceTypesListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedKafkaInstanceTypesListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedKafkaInstanceTypesListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedKafkaInstanceTypesListAllOf(val *SupportedKafkaInstanceTypesListAllOf) *NullableSupportedKafkaInstanceTypesListAllOf {
	return &NullableSupportedKafkaInstanceTypesListAllOf{value: val, isSet: true}
}

func (v NullableSupportedKafkaInstanceTypesListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedKafkaInstanceTypesListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

