/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkainstanceclient

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

type TopicsApi interface {

	/*
	 * CreateTopic Creates a new topic
	 * Creates a new topic for Kafka.
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiCreateTopicRequest
	 */
	CreateTopic(ctx _context.Context) ApiCreateTopicRequest

	/*
	 * CreateTopicExecute executes the request
	 * @return Topic
	 */
	CreateTopicExecute(r ApiCreateTopicRequest) (Topic, *_nethttp.Response, error)

	/*
	 * DeleteTopic Deletes a  topic
	 * Deletes the topic with the specified name.
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param topicName The topic name to delete.
	 * @return ApiDeleteTopicRequest
	 */
	DeleteTopic(ctx _context.Context, topicName string) ApiDeleteTopicRequest

	/*
	 * DeleteTopicExecute executes the request
	 */
	DeleteTopicExecute(r ApiDeleteTopicRequest) (*_nethttp.Response, error)

	/*
	 * GetTopic Retrieves the topic with the specified name.
	 * Topic
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param topicName The topic name to retrieve.
	 * @return ApiGetTopicRequest
	 */
	GetTopic(ctx _context.Context, topicName string) ApiGetTopicRequest

	/*
	 * GetTopicExecute executes the request
	 * @return Topic
	 */
	GetTopicExecute(r ApiGetTopicRequest) (Topic, *_nethttp.Response, error)

	/*
	 * GetTopics List of topics
	 * Returns a list of all of the available topics, or the list of topics that meet the users URL Query Parameters.
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiGetTopicsRequest
	 */
	GetTopics(ctx _context.Context) ApiGetTopicsRequest

	/*
	 * GetTopicsExecute executes the request
	 * @return TopicsList
	 */
	GetTopicsExecute(r ApiGetTopicsRequest) (TopicsList, *_nethttp.Response, error)

	/*
	 * UpdateTopic Updates the topic with the specified name.
	 * updates the topic with the new data.
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param topicName The topic name which is its unique id.
	 * @return ApiUpdateTopicRequest
	 */
	UpdateTopic(ctx _context.Context, topicName string) ApiUpdateTopicRequest

	/*
	 * UpdateTopicExecute executes the request
	 * @return Topic
	 */
	UpdateTopicExecute(r ApiUpdateTopicRequest) (Topic, *_nethttp.Response, error)
}

// TopicsApiService TopicsApi service
type TopicsApiService service

type ApiCreateTopicRequest struct {
	ctx           _context.Context
	ApiService    TopicsApi
	newTopicInput *NewTopicInput
}

func (r ApiCreateTopicRequest) NewTopicInput(newTopicInput NewTopicInput) ApiCreateTopicRequest {
	r.newTopicInput = &newTopicInput
	return r
}

func (r ApiCreateTopicRequest) Execute() (Topic, *_nethttp.Response, error) {
	return r.ApiService.CreateTopicExecute(r)
}

/*
 * CreateTopic Creates a new topic
 * Creates a new topic for Kafka.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiCreateTopicRequest
 */
func (a *TopicsApiService) CreateTopic(ctx _context.Context) ApiCreateTopicRequest {
	return ApiCreateTopicRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return Topic
 */
func (a *TopicsApiService) CreateTopicExecute(r ApiCreateTopicRequest) (Topic, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Topic
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TopicsApiService.CreateTopic")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/topics"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.newTopicInput == nil {
		return localVarReturnValue, nil, reportError("newTopicInput is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.newTopicInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteTopicRequest struct {
	ctx        _context.Context
	ApiService TopicsApi
	topicName  string
}

func (r ApiDeleteTopicRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.DeleteTopicExecute(r)
}

/*
 * DeleteTopic Deletes a  topic
 * Deletes the topic with the specified name.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param topicName The topic name to delete.
 * @return ApiDeleteTopicRequest
 */
func (a *TopicsApiService) DeleteTopic(ctx _context.Context, topicName string) ApiDeleteTopicRequest {
	return ApiDeleteTopicRequest{
		ApiService: a,
		ctx:        ctx,
		topicName:  topicName,
	}
}

/*
 * Execute executes the request
 */
func (a *TopicsApiService) DeleteTopicExecute(r ApiDeleteTopicRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TopicsApiService.DeleteTopic")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/topics/{topicName}"
	localVarPath = strings.Replace(localVarPath, "{"+"topicName"+"}", _neturl.PathEscape(parameterToString(r.topicName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetTopicRequest struct {
	ctx        _context.Context
	ApiService TopicsApi
	topicName  string
}

func (r ApiGetTopicRequest) Execute() (Topic, *_nethttp.Response, error) {
	return r.ApiService.GetTopicExecute(r)
}

/*
 * GetTopic Retrieves the topic with the specified name.
 * Topic
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param topicName The topic name to retrieve.
 * @return ApiGetTopicRequest
 */
func (a *TopicsApiService) GetTopic(ctx _context.Context, topicName string) ApiGetTopicRequest {
	return ApiGetTopicRequest{
		ApiService: a,
		ctx:        ctx,
		topicName:  topicName,
	}
}

/*
 * Execute executes the request
 * @return Topic
 */
func (a *TopicsApiService) GetTopicExecute(r ApiGetTopicRequest) (Topic, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Topic
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TopicsApiService.GetTopic")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/topics/{topicName}"
	localVarPath = strings.Replace(localVarPath, "{"+"topicName"+"}", _neturl.PathEscape(parameterToString(r.topicName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTopicsRequest struct {
	ctx        _context.Context
	ApiService TopicsApi
	offset     *int32
	limit      *int32
	size       *int32
	filter     *string
	page       *int32
	order      *string
	orderKey   *string
}

func (r ApiGetTopicsRequest) Offset(offset int32) ApiGetTopicsRequest {
	r.offset = &offset
	return r
}
func (r ApiGetTopicsRequest) Limit(limit int32) ApiGetTopicsRequest {
	r.limit = &limit
	return r
}
func (r ApiGetTopicsRequest) Size(size int32) ApiGetTopicsRequest {
	r.size = &size
	return r
}
func (r ApiGetTopicsRequest) Filter(filter string) ApiGetTopicsRequest {
	r.filter = &filter
	return r
}
func (r ApiGetTopicsRequest) Page(page int32) ApiGetTopicsRequest {
	r.page = &page
	return r
}
func (r ApiGetTopicsRequest) Order(order string) ApiGetTopicsRequest {
	r.order = &order
	return r
}
func (r ApiGetTopicsRequest) OrderKey(orderKey string) ApiGetTopicsRequest {
	r.orderKey = &orderKey
	return r
}

func (r ApiGetTopicsRequest) Execute() (TopicsList, *_nethttp.Response, error) {
	return r.ApiService.GetTopicsExecute(r)
}

/*
 * GetTopics List of topics
 * Returns a list of all of the available topics, or the list of topics that meet the users URL Query Parameters.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiGetTopicsRequest
 */
func (a *TopicsApiService) GetTopics(ctx _context.Context) ApiGetTopicsRequest {
	return ApiGetTopicsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return TopicsList
 */
func (a *TopicsApiService) GetTopicsExecute(r ApiGetTopicsRequest) (TopicsList, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  TopicsList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TopicsApiService.GetTopics")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/topics"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	if r.offset != nil {
		localVarQueryParams.Add("offset", parameterToString(*r.offset, ""))
	}
	if r.limit != nil {
		localVarQueryParams.Add("limit", parameterToString(*r.limit, ""))
	}
	if r.size != nil {
		localVarQueryParams.Add("size", parameterToString(*r.size, ""))
	}
	if r.filter != nil {
		localVarQueryParams.Add("filter", parameterToString(*r.filter, ""))
	}
	if r.page != nil {
		localVarQueryParams.Add("page", parameterToString(*r.page, ""))
	}
	if r.order != nil {
		localVarQueryParams.Add("order", parameterToString(*r.order, ""))
	}
	if r.orderKey != nil {
		localVarQueryParams.Add("orderKey", parameterToString(*r.orderKey, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateTopicRequest struct {
	ctx              _context.Context
	ApiService       TopicsApi
	topicName        string
	updateTopicInput *UpdateTopicInput
}

func (r ApiUpdateTopicRequest) UpdateTopicInput(updateTopicInput UpdateTopicInput) ApiUpdateTopicRequest {
	r.updateTopicInput = &updateTopicInput
	return r
}

func (r ApiUpdateTopicRequest) Execute() (Topic, *_nethttp.Response, error) {
	return r.ApiService.UpdateTopicExecute(r)
}

/*
 * UpdateTopic Updates the topic with the specified name.
 * updates the topic with the new data.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param topicName The topic name which is its unique id.
 * @return ApiUpdateTopicRequest
 */
func (a *TopicsApiService) UpdateTopic(ctx _context.Context, topicName string) ApiUpdateTopicRequest {
	return ApiUpdateTopicRequest{
		ApiService: a,
		ctx:        ctx,
		topicName:  topicName,
	}
}

/*
 * Execute executes the request
 * @return Topic
 */
func (a *TopicsApiService) UpdateTopicExecute(r ApiUpdateTopicRequest) (Topic, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPatch
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Topic
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TopicsApiService.UpdateTopic")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/topics/{topicName}"
	localVarPath = strings.Replace(localVarPath, "{"+"topicName"+"}", _neturl.PathEscape(parameterToString(r.topicName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.updateTopicInput == nil {
		return localVarReturnValue, nil, reportError("updateTopicInput is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateTopicInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
