/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * API version: 0.11.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkainstanceclient

import (
	"encoding/json"
)

// ListDeprecated struct for ListDeprecated
type ListDeprecated struct {

	Kind *string `json:"kind,omitempty"`

	Items []map[string]interface{} `json:"items"`

	// Total number of entries in the full result set
	Total int32 `json:"total"`

	// Number of entries per page (returned for fetch requests)
	Size *int32 `json:"size,omitempty"`

	// Current page number (returned for fetch requests)
	Page *int32 `json:"page,omitempty"`

}

// NewListDeprecated instantiates a new ListDeprecated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeprecated(items []map[string]interface{}, total int32) *ListDeprecated {
	this := ListDeprecated{}
	this.Items = items
	this.Total = total
	return &this
}

// NewListDeprecatedWithDefaults instantiates a new ListDeprecated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeprecatedWithDefaults() *ListDeprecated {
	this := ListDeprecated{}






	return &this
}


// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ListDeprecated) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeprecated) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ListDeprecated) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ListDeprecated) SetKind(v string) {
	o.Kind = &v
}


// GetItems returns the Items field value
func (o *ListDeprecated) GetItems() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListDeprecated) GetItemsOk() (*[]map[string]interface{}, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *ListDeprecated) SetItems(v []map[string]interface{}) {
	o.Items = v
}


// GetTotal returns the Total field value
func (o *ListDeprecated) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ListDeprecated) GetTotalOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ListDeprecated) SetTotal(v int32) {
	o.Total = v
}


// GetSize returns the Size field value if set, zero value otherwise.
func (o *ListDeprecated) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeprecated) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ListDeprecated) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ListDeprecated) SetSize(v int32) {
	o.Size = &v
}


// GetPage returns the Page field value if set, zero value otherwise.
func (o *ListDeprecated) GetPage() int32 {
	if o == nil || o.Page == nil {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeprecated) GetPageOk() (*int32, bool) {
	if o == nil || o.Page == nil {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ListDeprecated) HasPage() bool {
	if o != nil && o.Page != nil {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ListDeprecated) SetPage(v int32) {
	o.Page = &v
}


func (o ListDeprecated) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
    
	if true {
		toSerialize["items"] = o.Items
	}
    
	if true {
		toSerialize["total"] = o.Total
	}
    
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
    
	if o.Page != nil {
		toSerialize["page"] = o.Page
	}
    
	return json.Marshal(toSerialize)
}

type NullableListDeprecated struct {
	value *ListDeprecated
	isSet bool
}

func (v NullableListDeprecated) Get() *ListDeprecated {
	return v.value
}

func (v *NullableListDeprecated) Set(val *ListDeprecated) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeprecated) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeprecated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeprecated(val *ListDeprecated) *NullableListDeprecated {
	return &NullableListDeprecated{value: val, isSet: true}
}

func (v NullableListDeprecated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeprecated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

