/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectormgmtclient

import (
	"encoding/json"
)

// ConnectorNamespaceRequestMetaAnnotations struct for ConnectorNamespaceRequestMetaAnnotations
type ConnectorNamespaceRequestMetaAnnotations struct {

	Key string `json:"key"`

	Value string `json:"value"`

}

// NewConnectorNamespaceRequestMetaAnnotations instantiates a new ConnectorNamespaceRequestMetaAnnotations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorNamespaceRequestMetaAnnotations(key string, value string) *ConnectorNamespaceRequestMetaAnnotations {
	this := ConnectorNamespaceRequestMetaAnnotations{}
	this.Key = key
	this.Value = value
	return &this
}

// NewConnectorNamespaceRequestMetaAnnotationsWithDefaults instantiates a new ConnectorNamespaceRequestMetaAnnotations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorNamespaceRequestMetaAnnotationsWithDefaults() *ConnectorNamespaceRequestMetaAnnotations {
	this := ConnectorNamespaceRequestMetaAnnotations{}



	return &this
}


// GetKey returns the Key field value
func (o *ConnectorNamespaceRequestMetaAnnotations) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceRequestMetaAnnotations) GetKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ConnectorNamespaceRequestMetaAnnotations) SetKey(v string) {
	o.Key = v
}


// GetValue returns the Value field value
func (o *ConnectorNamespaceRequestMetaAnnotations) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceRequestMetaAnnotations) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ConnectorNamespaceRequestMetaAnnotations) SetValue(v string) {
	o.Value = v
}


func (o ConnectorNamespaceRequestMetaAnnotations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	
	if true {
		toSerialize["key"] = o.Key
	}
    
	if true {
		toSerialize["value"] = o.Value
	}
    
	return json.Marshal(toSerialize)
}

type NullableConnectorNamespaceRequestMetaAnnotations struct {
	value *ConnectorNamespaceRequestMetaAnnotations
	isSet bool
}

func (v NullableConnectorNamespaceRequestMetaAnnotations) Get() *ConnectorNamespaceRequestMetaAnnotations {
	return v.value
}

func (v *NullableConnectorNamespaceRequestMetaAnnotations) Set(val *ConnectorNamespaceRequestMetaAnnotations) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorNamespaceRequestMetaAnnotations) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorNamespaceRequestMetaAnnotations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorNamespaceRequestMetaAnnotations(val *ConnectorNamespaceRequestMetaAnnotations) *NullableConnectorNamespaceRequestMetaAnnotations {
	return &NullableConnectorNamespaceRequestMetaAnnotations{value: val, isSet: true}
}

func (v NullableConnectorNamespaceRequestMetaAnnotations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorNamespaceRequestMetaAnnotations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

