/*
 * Red Hat Openshift SmartEvents Fleet Manager V2
 *
 * The API exposed by the fleet manager of the SmartEvents service.
 *
 * API version: 0.0.1
 * Contact: openbridge-dev@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smarteventsmgmtclient

import (
	"encoding/json"
)

// ErrorListResponse struct for ErrorListResponse
type ErrorListResponse struct {
	Kind string `json:"kind"`
	Items *[]Error `json:"items,omitempty"`
	Page int64 `json:"page"`
	Size int64 `json:"size"`
	Total int64 `json:"total"`
}

// NewErrorListResponse instantiates a new ErrorListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorListResponse(kind string, page int64, size int64, total int64) *ErrorListResponse {
	this := ErrorListResponse{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	return &this
}

// NewErrorListResponseWithDefaults instantiates a new ErrorListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorListResponseWithDefaults() *ErrorListResponse {
	this := ErrorListResponse{}
	return &this
}

// GetKind returns the Kind field value
func (o *ErrorListResponse) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ErrorListResponse) GetKindOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ErrorListResponse) SetKind(v string) {
	o.Kind = v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ErrorListResponse) GetItems() []Error {
	if o == nil || o.Items == nil {
		var ret []Error
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorListResponse) GetItemsOk() (*[]Error, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ErrorListResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Error and assigns it to the Items field.
func (o *ErrorListResponse) SetItems(v []Error) {
	o.Items = &v
}

// GetPage returns the Page field value
func (o *ErrorListResponse) GetPage() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ErrorListResponse) GetPageOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ErrorListResponse) SetPage(v int64) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ErrorListResponse) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ErrorListResponse) GetSizeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ErrorListResponse) SetSize(v int64) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ErrorListResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ErrorListResponse) GetTotalOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ErrorListResponse) SetTotal(v int64) {
	o.Total = v
}

func (o ErrorListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableErrorListResponse struct {
	value *ErrorListResponse
	isSet bool
}

func (v NullableErrorListResponse) Get() *ErrorListResponse {
	return v.value
}

func (v *NullableErrorListResponse) Set(val *ErrorListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorListResponse(val *ErrorListResponse) *NullableErrorListResponse {
	return &NullableErrorListResponse{value: val, isSet: true}
}

func (v NullableErrorListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


