/*
 * Red Hat Openshift SmartEvents Fleet Manager V2
 *
 * The API exposed by the fleet manager of the SmartEvents service.
 *
 * API version: 0.0.1
 * Contact: openbridge-dev@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smarteventsmgmtclient

import (
	"encoding/json"
)

// ProcessorListResponse struct for ProcessorListResponse
type ProcessorListResponse struct {
	Kind string `json:"kind"`
	Items *[]ProcessorResponse `json:"items,omitempty"`
	Page int64 `json:"page"`
	Size int64 `json:"size"`
	Total int64 `json:"total"`
}

// NewProcessorListResponse instantiates a new ProcessorListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessorListResponse(kind string, page int64, size int64, total int64) *ProcessorListResponse {
	this := ProcessorListResponse{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	return &this
}

// NewProcessorListResponseWithDefaults instantiates a new ProcessorListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessorListResponseWithDefaults() *ProcessorListResponse {
	this := ProcessorListResponse{}
	return &this
}

// GetKind returns the Kind field value
func (o *ProcessorListResponse) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ProcessorListResponse) GetKindOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ProcessorListResponse) SetKind(v string) {
	o.Kind = v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ProcessorListResponse) GetItems() []ProcessorResponse {
	if o == nil || o.Items == nil {
		var ret []ProcessorResponse
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessorListResponse) GetItemsOk() (*[]ProcessorResponse, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ProcessorListResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ProcessorResponse and assigns it to the Items field.
func (o *ProcessorListResponse) SetItems(v []ProcessorResponse) {
	o.Items = &v
}

// GetPage returns the Page field value
func (o *ProcessorListResponse) GetPage() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ProcessorListResponse) GetPageOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ProcessorListResponse) SetPage(v int64) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ProcessorListResponse) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ProcessorListResponse) GetSizeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ProcessorListResponse) SetSize(v int64) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ProcessorListResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ProcessorListResponse) GetTotalOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ProcessorListResponse) SetTotal(v int64) {
	o.Total = v
}

func (o ProcessorListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableProcessorListResponse struct {
	value *ProcessorListResponse
	isSet bool
}

func (v NullableProcessorListResponse) Get() *ProcessorListResponse {
	return v.value
}

func (v *NullableProcessorListResponse) Set(val *ProcessorListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessorListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessorListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessorListResponse(val *ProcessorListResponse) *NullableProcessorListResponse {
	return &NullableProcessorListResponse{value: val, isSet: true}
}

func (v NullableProcessorListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessorListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


