name: Build
on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.openapi/**'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '.openapi/**'
      - '.github/**'

jobs:
  build:
    env:
      GOPATH: /home/runner/work/app-services-sdk-go/go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          base: main
          list-files: shell
          filters: |
            github:
              - '.github/**'
            openapi:
              - '.openapi/*'
            go:
              - '**.go'
      - run: echo ${{ steps.filter.outputs.openapi }}
      - name: Install Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version: 1.26.5
      - name: Check Go modules match source code
        run: ./scripts/go-mod-check.sh
      - name: golangci-lint
        if: steps.filter.outputs.go == 'true'
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout 2m0s
