name: Generate API client
on:
  repository_dispatch:
    types: [openapi-spec-change]

jobs:
  generate_client:
    env:
      APP_SERVICES_TOKEN: ${{ secrets.CI_USER_TOKEN }}
      BF2_TOKEN: ${{ secrets.BF2_TOKEN }}
      CLIENT_PAYLOAD: ${{ github.event.client_payload.github.repository }}
      GITHUB_REPO: "${{ github.event.client_payload.github.repository }}"
      OPENAPI_DIRECTORY: "${{ github.event.client_payload.openapi.directory}}"
      OPENAPI_FILENAME: "${{ github.event.client_payload.openapi.filename }}"
      BRANCH: "main"  

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: ./hack/scripts/generate.sh
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "Update API client"
          token: "${{ env.APP_SERVICES_TOKEN }}"
          commit-message: "chore: generate API client"
          delete-branch: true
          reviewers: craicoverflow
          body: |
            Auto-generated API client
