
name: Generate API client
on:
  repository_dispatch:
    types: [openapi-spec-change]

jobs:
  generate_client:
    env:
      GOPATH: /home/runner/work/app-services-sdk-go/go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch OpenAPI schema
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin

          # fetch API spec
          go get -u github.com/redhat-developer/app-services-sdk-go/internal/apigen/cmd/api-fetch@main
          api-fetch --download-url=${{ github.event.client_payload.download_url }} --token=${{ secrets.BF2_TOKEN }}
          
          # generate API client
          go get -u github.com/redhat-developer/app-services-sdk-go/internal/apigen/cmd/api-generate@main
          api-generate --client-id=${{ github.event.client_payload.id }} --download-url=${{ github.event.client_payload.download_url}} --generator=go --templates-dir="./scripts/templates" --repo-metadata ".config/api-client-metadata.json"
        
          # create Pull Request
          go get -u github.com/redhat-developer/app-services-sdk-go/internal/apigen/cmd/api-create-pr@main
          go mod tidy
          api-create-pr --repo-metadata ".config/api-client-metadata.json" --client-id=${{ github.event.client_payload.id }} --token=${{ secrets.CI_USER_TOKEN }} --author="app-services-ci" --owner="redhat-developer" --repo="app-services-sdk-go"