name: Generate API client
on:
  repository_dispatch:
    types: [openapi-spec-change]

jobs:
  generate_client:
    env:
      APP_SERVICES_TOKEN: "${{ secrets.CI_USER_TOKEN }}"
      BF2_TOKEN: "${{ secrets.BF2_TOKEN }}"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: ./scripts/fetch_api.sh ${{ github.event.client_payload.download_url }}
      - run: ./scripts/generate_go.sh ${{ github.event.client_payload.id }} ${{ github.event.client_payload.download_url }}
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "Update API client"
          token: "${{ env.APP_SERVICES_TOKEN }}"
          commit-message: "chore: generate API client"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          delete-branch: true
          reviewers: "craicoverflow, wtrocki"
          body: |
            Auto-generated API client
